CREATE TABLE ACCOUNTS (
    ID IDENTITY NOT NULL,
    CURRENCY CHAR(3) NOT NULL,
    BALANCE DECIMAL(20, 2) NOT NULL DEFAULT 0,
    OWNER VARCHAR(56),
);
INSERT INTO ACCOUNTS (CURRENCY) VALUES ('RUR');
INSERT INTO ACCOUNTS (CURRENCY) VALUES ('USD');
INSERT INTO ACCOUNTS (CURRENCY) VALUES ('EUR');
INSERT INTO ACCOUNTS (CURRENCY) VALUES ('YEN');